apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex280-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex280-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex288-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex288-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex370-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex370-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex380-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex380-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex480-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex480-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: ex482-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: ex482-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
--------------

apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-quota
namespace: sandbox-lab
spec:
hard:
requests.cpu: "2"
requests.memory: 4Gi
limits.cpu: "4"
limits.memory: 8Gi
pods: "20"
----------

apiVersion: v1
kind: LimitRange
metadata:
name: default-limits
namespace: sandbox-lab
spec:
limits:
- type: Container
default:
cpu: "500m"
memory: "512Mi"
defaultRequest:
cpu: "100m"
memory: "128Mi"
max:
cpu: "1"
memory: "1Gi"
min:
cpu: "50m"
memory: "64Mi"
