apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-expand-test
  namespace: ex370-capacity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-ceph-rbd-expandable
