apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: ex370-capacity
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "200Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limits
  namespace: ex370-capacity
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 100Gi
    min:
      storage: 1Gi
